GET http://localhost:3001/api/persons

###

GET http://localhost:3001/info

###

POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name": "This is a new person",
  "number": "123-4567890"
}

###

DELETE http://localhost:3001/api/persons/5
