GET http://localhost:3001/api/persons

###

GET http://localhost:3001/info

###

POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name": "This is a new person 2",
  "number": "123456879"
}

###

DELETE http://localhost:3001/api/persons/5
